"""
Django settings for estatecrm project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%2^y20*&+k-&-42$9)ko9nwd0npvczz&k6a7govczs0(6s0xv@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Third party apps
    'crispy_forms',
    'crispy_tailwind',
    'django_cleanup',
    'import_export',
    'sorl.thumbnail',
    'pwa',
    'tailwind',
        
    # Local apps
    'accounts',
    'properties',
    'realtors',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'estatecrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'estatecrm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
from estatecrm.keys import db
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'estatecrmdb',
        'USER': 'postgres',
        'PASSWORD': db['db'],
        'HOST':'localhost'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'el'


TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale/'),
)

LANGUAGES = (
    ('el', _('Greek')),
    ('en', _('English')),
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'estatecrm/static')
]
STATIC_ROOT = os.path.join(BASE_DIR,'static')

# Messages - Alerts
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert_debug',
    messages.INFO: 'alert_info',
    messages.SUCCESS: 'alert_success',
    messages.WARNING: 'alert_warning',
    messages.ERROR: 'alert_danger',
}

# Media folder
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Auth - Login
AUTH_USER_MODEL = 'accounts.CustomUser'
LOGIN_REDIRECT_URL = 'landing-page'
LOGOUT_REDIRECT_URL = 'landing-page'
LOGIN_URL = '/login'

# Crispy Forms
CRISPY_TEMPLATE_PACK = 'tailwind'
CRISPY_ALLOWED_TEMPLATE_PACKS = 'tailwind'

DATE_INPUT_FORMATS = ['%d-%m-%Y']
DATETIME_INPUT_FORMATS = ['%d-%m-%Y %H:%M:%S']

# PWA
PWA_APP_NAME = 'Yeneses'
PWA_APP_DESCRIPTION = "Yeneses - Property search engine"
PWA_APP_THEME_COLOR = '#3b82f6'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/js', 'serviceworker.js')
PWA_APP_ICONS = [
    {
        'src': '/static/images/yeneses_pwa_512px.png',
        #'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)',
        'sizes': '512x512',
        "type": "image/png"
    },
    {
        'src': '/static/images/yeneses_pwa_160px.png',
        'sizes': '160x160',
        "type": "image/png"
    },
    {
        'src': '/static/images/yeneses_pwa_192px.png',
        'sizes': '192x192',
        "type": "image/png"
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/images/yeneses_pwa_160px.png',
        'sizes': '160x160',
        "type": "image/png"
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/yeneses_pwa_512px.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)',
        'sizes': '512x512',
        "type": "image/png"
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-gb'

# Email
from estatecrm.keys import mail
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'themistheodoratos@outlook.com'
EMAIL_HOST_PASSWORD = mail['mail']
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'themistheodoratos@outlook.com'

# Primary key django > 3.2
DEFAULT_AUTO_FIELD='django.db.models.AutoField'

# Production settings
try:
    from .local_settings import *
except ImportError:
    pass
