# Generated by Django 3.2.5 on 2021-11-10 16:55

from django.db import migrations, models
import properties.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='Signed up as agent?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_realtor',
            field=models.BooleanField(default=False, verbose_name='Signed up as realtor?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture/%Y/%m/%d/', validators=[properties.validators.validate_file_size], verbose_name='Profile picture'),
        ),
    ]
