# Generated by Django 3.1.4 on 2021-03-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
    ]
