# Generated by Django 3.1.4 on 2021-03-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_glabalmappings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlabalMappings',
            new_name='GlobalMapping',
        ),
    ]
