# Generated by Django 3.1.4 on 2021-03-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210326_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalMapping',
        ),
    ]
