# Generated by Django 3.1.4 on 2021-04-26 21:39

from django.db import migrations, models
import properties.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture/%Y/%m/%d/', validators=[properties.validators.validate_file_size]),
        ),
    ]
