# Generated by Django 3.1.4 on 2021-05-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='furniture',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='m2',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='photo_main',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='price',
        ),
    ]
