# Generated by Django 3.1.4 on 2021-03-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='short_description',
            field=models.CharField(default='', max_length=120),
        ),
    ]
