# Generated by Django 3.1.4 on 2021-03-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_properties_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='short_description',
            field=models.TextField(default='', max_length=120),
        ),
    ]
