# Generated by Django 3.1.4 on 2021-05-08 16:38

from django.db import migrations, models
import properties.validators


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210508_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='bedrooms',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='furniture',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Unfurnished', 'Unfurnished')], default='Furnished', max_length=11),
        ),
        migrations.AddField(
            model_name='properties',
            name='garage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='properties',
            name='m2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='photo_main',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/', validators=[properties.validators.validate_file_size]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='price',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
