# Generated by Django 3.1.4 on 2021-05-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20210508_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='search_address',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='properties',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
