# Generated by Django 3.1.4 on 2021-04-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20210330_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='bedrooms',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
