# Generated by Django 3.1.4 on 2021-05-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20210508_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='geo_lat',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='properties',
            name='geo_lng',
            field=models.CharField(max_length=15),
        ),
    ]
