# Generated by Django 3.1.4 on 2021-04-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20210401_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='geo_lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='properties',
            name='geo_lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
    ]
