# Generated by Django 3.1.4 on 2021-04-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20210405_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='geo_lat',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='properties',
            name='geo_lng',
            field=models.CharField(max_length=10),
        ),
    ]
