# Generated by Django 3.1.4 on 2021-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20210405_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='title',
        ),
        migrations.AddField(
            model_name='properties',
            name='property_type',
            field=models.CharField(default='Studio', max_length=100),
            preserve_default=False,
        ),
    ]
