# Generated by Django 3.1.4 on 2021-05-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_geodata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='locality',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='administrative_area_level_1',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='administrative_area_level_2',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='administrative_area_level_3',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='administrative_area_level_4',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='administrative_area_level_5',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='main_type',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='political',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='postal_town',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='premise',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='route',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='search_address',
        ),
    ]
