# Generated by Django 3.1.4 on 2021-04-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20210406_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='furniture',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Unfurnished', 'Unfurnished')], default='Furnished', max_length=11),
        ),
    ]
