# Generated by Django 3.1.4 on 2021-05-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20210515_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='identifier_1',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='identifier_2',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='properties',
            name='street_number',
            field=models.CharField(max_length=200),
        ),
    ]
