# Generated by Django 3.1.4 on 2021-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_properties_furniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='short_description',
            field=models.TextField(default='', max_length=150),
        ),
    ]
