# Generated by Django 3.1.4 on 2021-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20210515_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='admin_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='admin_1_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='admin_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='admin_2_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='admin_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='admin_3_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='admin_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='admin_4_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='country_en',
            field=models.CharField(default='Greece', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='m2',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='postalcode',
            field=models.CharField(max_length=6),
        ),
    ]
