# Generated by Django 3.1.4 on 2021-04-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20210407_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='currency',
            field=models.CharField(choices=[('euros', '€'), ('pounds', '£'), ('dollars', '$')], default='euros', max_length=10),
        ),
    ]
