# Generated by Django 3.1.4 on 2021-05-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20210515_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='geoSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('identifier', models.SmallIntegerField()),
            ],
        ),
    ]
