# Generated by Django 3.1.4 on 2021-04-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_properties_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='currency',
            field=models.CharField(choices=[('€', 'euros(€)'), ('£', 'pounds(£)'), ('$', 'dollars($)')], default='euros', max_length=10),
        ),
    ]
