# Generated by Django 3.1.4 on 2021-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_geosearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geosearch',
            name='identifier',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='properties',
            name='identifier_1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='properties',
            name='identifier_2',
            field=models.CharField(max_length=12),
        ),
    ]
