# Generated by Django 3.1.4 on 2021-04-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20210412_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_category',
            field=models.CharField(choices=[('FEATURED', 'FEATURED'), ('OPPORTUNITY', 'OPPORTUNITY'), ('', 'STANDARD')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='properties',
            name='currency',
            field=models.CharField(choices=[('€', 'euros(€)'), ('£', 'pounds(£)'), ('$', 'dollars($)')], default='€', max_length=10),
        ),
    ]
