# Generated by Django 3.1.4 on 2021-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20210415_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_category',
            field=models.CharField(choices=[('FEATURED', 'FEATURED'), ('OPPORTUNITY', 'OPPORTUNITY'), ('STANDARD', '')], default='', max_length=25),
        ),
    ]
