# Generated by Django 3.1.4 on 2021-05-20 15:11

from django.db import migrations, models
import properties.validators


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_auto_20210516_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='location',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='geodata',
            name='location_en',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='properties',
            name='postalcode',
            field=models.CharField(max_length=6, validators=[properties.validators.validate_postcode]),
        ),
    ]
