# Generated by Django 3.1.4 on 2021-04-15 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_auto_20210415_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='available_after',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
