# Generated by Django 3.1.4 on 2021-05-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_auto_20210520_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='geoSearch',
        ),
        migrations.AlterField(
            model_name='geodata',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
