# Generated by Django 3.1.4 on 2021-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_properties_available_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='agency_description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
