# Generated by Django 3.1.4 on 2021-04-16 16:38

from django.db import migrations, models
import properties.validators


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_properties_agency_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='photo_main',
            field=models.FileField(upload_to='photos/%Y/%m/%d/', validators=[properties.validators.validate_file_size]),
        ),
    ]
