# Generated by Django 3.1.4 on 2021-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_auto_20210520_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='admin_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='admin_1_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
