# Generated by Django 3.1.4 on 2021-05-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_auto_20210521_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='identifier_1',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='identifier_2',
        ),
        migrations.AddField(
            model_name='properties',
            name='identifier',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='properties.geodata'),
            preserve_default=False,
        ),
    ]
