# Generated by Django 3.1.4 on 2021-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_auto_20210416_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='for_sale',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='to_rent',
        ),
        migrations.AddField(
            model_name='properties',
            name='advertised',
            field=models.CharField(choices=[('For_Sale', 'For Sale'), ('To_Rent', 'To Rent')], default='To_Rent', max_length=10),
        ),
    ]
