# Generated by Django 3.1.4 on 2021-04-17 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_realtor_realtor_description'),
        ('properties', '0021_auto_20210417_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor'),
        ),
    ]
