# Generated by Django 3.1.4 on 2021-04-17 22:46

from django.db import migrations, models
import properties.validators


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_auto_20210417_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[properties.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[properties.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[properties.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[properties.validators.validate_file_size]),
        ),
    ]
