# Generated by Django 3.1.4 on 2021-04-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_auto_20210417_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='realtor',
        ),
    ]
