# Generated by Django 3.1.4 on 2021-04-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_remove_properties_realtor'),
        ('realtors', '0008_auto_20210428_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.organisation'),
            preserve_default=False,
        ),
    ]
