# Generated by Django 3.1.4 on 2021-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_auto_20210619_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='short_description',
            field=models.TextField(default='', max_length=180),
        ),
    ]
