# Generated by Django 3.1.4 on 2021-04-29 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0009_agent'),
        ('properties', '0025_properties_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtors.agent'),
        ),
    ]
