# Generated by Django 3.2.5 on 2021-08-27 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0026_auto_20210620_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='saved_property',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
