# Generated by Django 3.2.5 on 2021-08-27 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0028_auto_20210827_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPropertyFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=1500)),
                ('favourite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
