# Generated by Django 3.2.5 on 2021-10-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_alter_userpropertyfavourite_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.geodata'),
        ),
    ]
