# Generated by Django 3.2.5 on 2021-10-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_alter_properties_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_feature',
            field=models.CharField(choices=[('', ''), ('energy_efficient', 'Energy Efficient'), ('garage', 'Garage'), ('open_plan', 'Open Plan'), ('new_construction', 'New Construction'), ('modern', 'Modern'), ('classic', 'Classic'), ('fireplace', 'Fireplace'), ('garden', 'Garden')], default='', max_length=100),
        ),
    ]
