# Generated by Django 3.2.5 on 2021-10-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_alter_properties_property_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_feature',
            field=models.CharField(blank=True, choices=[('', ''), ('Energy Efficient', 'Energy Efficient'), ('Garage', 'Garage'), ('Open Plan', 'Open Plan'), ('New Construction', 'New Construction'), ('Modern', 'Modern'), ('Classic', 'Classic'), ('Fireplace', 'Fireplace'), ('Garden', 'Garden')], default='', max_length=100),
        ),
    ]
