# Generated by Django 3.1.4 on 2021-04-16 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='country_code',
            field=models.CharField(default='+302', max_length=6),
        ),
        migrations.AddField(
            model_name='realtor',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='realtor',
            name='phone',
            field=models.CharField(default=1232143, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='email',
            field=models.EmailField(default='teo@gmail.com', max_length=254),
        ),
    ]
