# Generated by Django 3.1.4 on 2021-04-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20210416_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='realtor_description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
