# Generated by Django 3.1.4 on 2021-04-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_realtor_realtor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='realtor_logo',
            field=models.ImageField(blank=True, upload_to='realtor_logos/%Y/%m/%d/'),
        ),
    ]
