# Generated by Django 3.1.4 on 2021-04-28 15:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import properties.validators


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_remove_properties_realtor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtors', '0007_auto_20210417_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('country_code', models.CharField(blank=True, max_length=6)),
                ('organisation_description', models.TextField(blank=True, max_length=250)),
                ('organisation_logo', models.ImageField(blank=True, upload_to='organisation_logos/%Y/%m/%d/', validators=[properties.validators.validate_file_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Realtor',
        ),
    ]
