# Generated by Django 3.1.4 on 2021-04-29 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0009_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
