# Generated by Django 3.1.4 on 2021-04-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0010_agent_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='active_agent',
            field=models.BooleanField(default=True),
        ),
    ]
